const express = require ('express');
const bodyparser = require ('body-parser');
const app = express ();
app.use (bodyparser.urlencoded ({extended: true}));
app.use (bodyparser.json ());
const port = process.env.PORT || 3000;
console.log ('RESTful API server started on: ' + port);
const routes = require ('./api/users/routes/routes');
routes (app);
app.listen (port);
